export const FORMAT_CONFIGS = {
  reel_9x16: {
    compositionId: 'ReelComposition',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDuration: 90,
    codec: 'h264',
    bitrate: '8M',
    audioBitrate: '192k',
    propOverrides: {},
    platform: 'instagram',
  },
  tiktok_9x16: {
    compositionId: 'ReelComposition',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDuration: 180,
    codec: 'h264',
    bitrate: '6M',
    audioBitrate: '128k',
    propOverrides: {
      showProgressBar: false,
    },
    platform: 'tiktok',
  },
  feed_1x1: {
    compositionId: 'FeedComposition',
    width: 1080,
    height: 1080,
    fps: 30,
    maxDuration: 60,
    codec: 'h264',
    bitrate: '6M',
    audioBitrate: '192k',
    propOverrides: {
      letterbox: true,
    },
    platform: 'instagram',
  },
  feed_4x5: {
    compositionId: 'FeedComposition',
    width: 1080,
    height: 1350,
    fps: 30,
    maxDuration: 60,
    codec: 'h264',
    bitrate: '7M',
    audioBitrate: '192k',
    propOverrides: {},
    platform: 'instagram',
  },
  story_9x16: {
    compositionId: 'StoryComposition',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDuration: 60,
    codec: 'h264',
    bitrate: '6M',
    audioBitrate: '128k',
    propOverrides: {
      safeAreaTop: 120,
      safeAreaBottom: 200,
    },
    platform: 'instagram',
  },
} as const;

export type ExportFormat = keyof typeof FORMAT_CONFIGS;
