export const NICHES = {
  fitness: {
    id: 'fitness',
    name: 'Fitness & Health',
    icon: 'Dumbbell',
    defaultEffects: ['zoom_punch', 'flash_on_beat'],
    defaultTransitions: ['cut', 'whip_pan'],
    captionStyle: 'pop',
    pacing: 'fast',
    hookStrategy: 'before_after',
    ctaStyle: 'follow_for_more',
    colorPalette: ['#FF6B35', '#004E89', '#FFFFFF'],
    musicMood: 'energetic',
  },
  tech: {
    id: 'tech',
    name: 'Tech & SaaS',
    icon: 'Monitor',
    defaultEffects: ['screen_zoom', 'cursor_highlight'],
    defaultTransitions: ['slide', 'morph'],
    captionStyle: 'word-highlight',
    pacing: 'medium',
    hookStrategy: 'problem_statement',
    ctaStyle: 'link_in_bio',
    colorPalette: ['#6366F1', '#0F172A', '#F8FAFC'],
    musicMood: 'ambient',
  },
  food: {
    id: 'food',
    name: 'Food & Recipe',
    icon: 'ChefHat',
    defaultEffects: ['slow_zoom', 'warm_grade'],
    defaultTransitions: ['dissolve', 'cut'],
    captionStyle: 'karaoke',
    pacing: 'medium',
    hookStrategy: 'end_result_first',
    ctaStyle: 'save_recipe',
    colorPalette: ['#F59E0B', '#78350F', '#FFF7ED'],
    musicMood: 'upbeat_acoustic',
  },
  education: {
    id: 'education',
    name: 'Education & Tutorial',
    icon: 'BookOpen',
    defaultEffects: ['text_callout', 'arrow_annotation'],
    defaultTransitions: ['slide', 'fade'],
    captionStyle: 'word-highlight',
    pacing: 'slow',
    hookStrategy: 'curiosity_gap',
    ctaStyle: 'follow_for_tips',
    colorPalette: ['#10B981', '#1E293B', '#F0FDF4'],
    musicMood: 'calm',
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'E-commerce & Product',
    icon: 'ShoppingBag',
    defaultEffects: ['product_spotlight', 'price_flash'],
    defaultTransitions: ['zoom', 'slide'],
    captionStyle: 'glow',
    pacing: 'fast',
    hookStrategy: 'urgency',
    ctaStyle: 'shop_now',
    colorPalette: ['#EC4899', '#18181B', '#FDF2F8'],
    musicMood: 'trendy',
  },
  podcast: {
    id: 'podcast',
    name: 'Podcast & Talking Head',
    icon: 'Mic',
    defaultEffects: ['speaker_zoom', 'waveform_bg'],
    defaultTransitions: ['cut'],
    captionStyle: 'word-highlight',
    pacing: 'dynamic',
    hookStrategy: 'controversial_quote',
    ctaStyle: 'full_episode_link',
    colorPalette: ['#8B5CF6', '#0F0F0F', '#F5F3FF'],
    musicMood: 'none',
  },
} as const;

export type NicheId = keyof typeof NICHES;
